### ISSUE TITLE
Reporter stops with fatal error when newman is run with --timeout-request option

### ISSUE THREAD

**Issue by David-Kozina-SA** [ervirendersingh/newman-reporter-allure#24]
**Environment:**
newman-reporter-allure version: 1.0.7
newman version: 5.3.2
OS: Ubuntu 20.04

# What is happening:
If we try to use `npx newman run <collection> --timeout-request 60000 -r allure --reporter-allure-export allure-results` and any request is actually timeouted the allure reporter will fail fatally with the error and whole test execution is stopped and no further report is generated. Not using --timeout-request at all produce no such behavior. Using --timeout-request with json and cli reporters also do not produce this error.

# What is expected:
If we try to use `--timeout-request 60000` while running *newman* with allure reporter there would not be a fatal error if timeout is applied.

# What is causing the error:
As seen in the log below the reason for this error is the fact that the timeouted request passed to reporter from newman is undefined.

## log:
```bash
__postmanruntime_fatal_debug: instruction.execute callback called twice
TypeError: Cannot read properties of undefined (reading 'method')
    at AllureReporter.item (/home/user/Documents/stress-test-probe/node_modules/newman-reporter-allure/index.js:311:59)
    at EventEmitter.<anonymous> (/home/user/Documents/stress-test-probe/node_modules/newman-reporter-allure/index.js:22:103)
    at EventEmitter.emit (/home/user/Documents/stress-test-probe/node_modules/eventemitter3/index.js:203:33)
    at Function.callbacks.<computed> [as item] (/home/user/Documents/stress-test-probe/node_modules/newman/lib/run/index.js:213:34)
    at PostmanCollectionRun.<anonymous> (/home/user/Documents/stress-test-probe/node_modules/postman-runtime/lib/runner/extensions/item.command.js:254:47)
    at apply (/home/user/Documents/stress-test-probe/node_modules/lodash/lodash.js:489:27)
    at /home/user/Documents/stress-test-probe/node_modules/lodash/lodash.js:9541:36
    at /home/user/Documents/stress-test-probe/node_modules/lodash/lodash.js:4943:15
    at Function.<anonymous> (/home/user/Documents/stress-test-probe/node_modules/lodash/lodash.js:9540:7)
    at apply (/home/user/Documents/stress-test-probe/node_modules/lodash/lodash.js:490:27)
    at Function.invokeMap (/home/user/Documents/stress-test-probe/node_modules/lodash/lodash.js:6627:16)
    at Instruction.<anonymous> (/home/user/Documents/stress-test-probe/node_modules/postman-runtime/lib/runner/instruction.js:148:48)
    at PostmanCollectionRun.<anonymous> (/home/user/Documents/stress-test-probe/node_modules/postman-runtime/lib/runner/extensions/event.command.js:532:17)
    at /home/user/Documents/stress-test-probe/node_modules/async/dist/async.js:251:13
    at wrapper (/home/user/Documents/stress-test-probe/node_modules/async/dist/async.js:271:20)
    at replenish (/home/user/Documents/stress-test-probe/node_modules/async/dist/async.js:441:29)
```

**Comment by vovsemenv** [comment]
Hello, this repo will be archived. New versions of the newman-reporter-allure will be maintained in the allure framework repo. https://github.com/allure-framework/allure-js

This issue is fixed in the newman-reporter-allure@2.0.0-beta.21
